// SPDX-License-Identifier: MIT

#ifndef WLAN_PROBE_DIAGNOSIS_H
#define WLAN_PROBE_DIAGNOSIS_H

#include "probe.h"

typedef enum
{
    PROBE_DIAGNOSIS_AHB_MISSING,
    PROBE_DIAGNOSIS_CONTROLLER_UNREADABLE,
    PROBE_DIAGNOSIS_HOST_SETUP_FAILED,
    PROBE_DIAGNOSIS_CMD5_SIGNAL_ERROR,
    PROBE_DIAGNOSIS_CMD5_NO_RESPONSE,
    PROBE_DIAGNOSIS_CARD_NOT_READY,
    PROBE_DIAGNOSIS_ENUMERATION_FAILED,
    PROBE_DIAGNOSIS_CCCR_FAILED,
    PROBE_DIAGNOSIS_CIS_FAILED,
    PROBE_DIAGNOSIS_FUNCTION_START_FAILED,
    PROBE_DIAGNOSIS_SSB_WINDOW_FAILED,
    PROBE_DIAGNOSIS_DATA_TRANSFER_FAILED,
    PROBE_DIAGNOSIS_SSB_IDENTITY_INVALID,
    PROBE_DIAGNOSIS_PASSED
} probe_diagnosis;

probe_diagnosis probe_classify(const probe_result *result);
const char *probe_diagnosis_code(probe_diagnosis diagnosis);

#endif
